add support for bootstrapping hooks

diff --git a/meta-tedge-common/recipes-tedge/tedge-bootstrap/tedge-bootstrap/tedge-bootstrap b/meta-tedge-common/recipes-tedge/tedge-bootstrap/tedge-bootstrap/tedge-bootstrap
--- a/meta-tedge-common/recipes-tedge/tedge-bootstrap/tedge-bootstrap/tedge-bootstrap
+++ b/meta-tedge-common/recipes-tedge/tedge-bootstrap/tedge-bootstrap/tedge-bootstrap
@@ -31,36 +31,6 @@ init_tedge_data() {
     fi
 }
 
-set_hostname() {
-    host_name="$1"
-    if [ "$(cat /etc/hostname)" = "$host_name" ]; then
-        echo "Host name is already set"
-        return
-    fi
-
-    if [ -w /etc/hostname ]; then
-        echo "$host_name" | tee /etc/hostname
-    else
-        echo "Skipping setting hostname as /etc/hostname is not writable"
-    fi
-
-    if [ -w /etc/hosts ]; then
-        sed -i -E 's/^127.0.1.1.*/127.0.1.1\t'"$host_name"'/' /etc/hosts
-    else
-        echo "Skipping setting hosts as /etc/hosts is not writable"
-    fi
-
-    if [ -w /etc/hostname ]; then
-        hostnamectl set-hostname "$host_name" || log "Failed to set using hostnamectl"
-    else
-        echo "Skipping setting hostname via hostnamectl set-hostname as /etc/hostname is not writable"
-    fi
-
-    if command -V systemctl >/dev/null 2>&1; then
-        systemctl restart avahi-daemon --no-block 2>/dev/null ||:
-    fi
-}
-
 # set hostname
 DEVICE_ID=
 attempt=0
@@ -77,6 +47,17 @@ done
 
 init_tedge_data
 
-set_hostname "$DEVICE_ID"
+# Run bootstrapping hooks
+_NEWLINE=$(printf '\n')
+find -L "$RUN_PARTS" -type f -name "$NAME_FILTER" -perm 755 | while IFS="$_NEWLINE" read -r file
+do
+    echo "Executing bootstrap script: $file" >&2
+    if "$file" "$DEVICE_ID"; then
+        log "bootstrap hook ($file) was successful"
+    else
+        log "boostrap hook ($file) failed. Exiting..."
+        exit 1
+    fi
+done
 
 touch "$RAN_MARKER"
